# Serena Project Configuration for NodeVision Editor _V2

# プロジェクト名
project_name: "NodeVision Editor _V2"

# プロジェクトのルートパス
project_root: "/Users/apple/Desktop/AI アプリ/NodeVision Editor _V2"

# プロジェクトの説明
description: "NodeVision Editor - A sophisticated video editing application built with Electron, TypeScript, and FFmpeg"

# プログラミング言語
languages:
  - typescript

# インデックス対象のディレクトリ
include_paths:
  - "apps/"
  - "packages/"

# 除外するパス
exclude_paths:
  - "node_modules/"
  - "dist/"
  - ".git/"
  - "*.log"
  - "coverage/"
  - ".pnpm-store/"

# ファイル拡張子のフィルター
file_extensions:
  - ".ts"
  - ".js"
  - ".json"
  - ".md"

# プロジェクトの主要なエントリーポイント
entry_points:
  - "apps/desktop-electron/src/main.ts"
  - "apps/desktop-electron/src/renderer/app.ts"

# 依存関係の管理ツール
package_manager: "pnpm"

# ビルドシステム
build_system: "typescript"
